name: Java CI with Gradle

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  should_run:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List new commits
        run: |
            echo "Checking for new commits";
            git log --since="15 minutes ago" --oneline;
            echo "---";
      
      - name: Check if new commits exist
        id: should_run
        run: | 
          if git log --since="15 minutes ago" --pretty=format:"%h - %an" | grep -q "-"; then
              echo "should_run=true" >> $GITHUB_OUTPUT
          else
              echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  test:
    needs: should_run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print should_run
        run: |
            echo "---";
            echo "should_run: ${{ needs.should_run.outputs.should_run }}";
            echo "---";