name: Java CI with Gradle

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  should_run:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List new commits
        id: should_run
        run: |
            echo "Checking for new commits"
            git log --since="10 minutes ago" --oneline
            echo "---"
      
      - name: Check if new commits exist
        id: get_commit
        run: | 
          if git log --since="5 minutes ago" --pretty=format:"%h - %an" | grep -q "-"; then
              echo "should_run=true" >> $GITHUB_ENV
          else
              echo "should_run=false" >> $GITHUB_ENV
          fi

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print should_run
        run: echo ${{ needs.should_run.outputs.should_run }}